# This file is part of the Ssstr string library.
# Copyright 2022-2023 Board of Regents of the University of Wisconsin System
# SPDX-License-Identifier: MIT

line-length = 79

[lint]
select = ["E", "F", "UP", "B", "SIM", "I"]
ignore = ["B011", "E501"]
